SERVER-17063 fixed filemd5 compilation error: control reaches end of non-void function
(cherry picked from commit 2da61e7f9e54f6e398b472fd945e786d64c6de88 [formerly 2bde42b58c09c90aaf529f6bedea9c1bd76e91dd])


Former-commit-id: ac7ccbf18ce072a4b8ace91cbb85d9bc2a6c6a23