SERVER-38319 fix windows compiler error C2885
(cherry picked from commit e91ad0c9e1c38191452d60df47bb57b160b75ecc [formerly 5a6563e7371ee792973ba19af23f7857ceecd546])


Former-commit-id: c85c6b3f22e9b6f0ce60c33d9fd00a7ff991e703